/* Generated By:JavaCC: Do not edit this line. GrammarConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int SOP = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int PUBLIC = 14;
  /** RegularExpression Id. */
  int STATIC = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int MAIN = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int EXTENDS = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int BOOLEAN = 22;
  /** RegularExpression Id. */
  int LENGTH = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int THIS = 26;
  /** RegularExpression Id. */
  int NEW = 27;
  /** RegularExpression Id. */
  int DOT = 28;
  /** RegularExpression Id. */
  int SEMICOLON = 29;
  /** RegularExpression Id. */
  int COMMA = 30;
  /** RegularExpression Id. */
  int EXCL = 31;
  /** RegularExpression Id. */
  int ASSIGN = 32;
  /** RegularExpression Id. */
  int BRACE_L = 33;
  /** RegularExpression Id. */
  int BRACE_R = 34;
  /** RegularExpression Id. */
  int PAREN_L = 35;
  /** RegularExpression Id. */
  int PAREN_R = 36;
  /** RegularExpression Id. */
  int BRACKET_L = 37;
  /** RegularExpression Id. */
  int BRACKET_R = 38;
  /** RegularExpression Id. */
  int SUM = 39;
  /** RegularExpression Id. */
  int SUB = 40;
  /** RegularExpression Id. */
  int MULTI = 41;
  /** RegularExpression Id. */
  int LESSTHAN = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int MIN_LET = 45;
  /** RegularExpression Id. */
  int MAI_LET = 46;
  /** RegularExpression Id. */
  int LET = 47;
  /** RegularExpression Id. */
  int UNDERSCORE = 48;
  /** RegularExpression Id. */
  int ID = 49;
  /** RegularExpression Id. */
  int NUM = 50;
  /** RegularExpression Id. */
  int REAL = 51;
  /** RegularExpression Id. */
  int ERR = 52;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int singlelinecomment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"//\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"System.out.println\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"extends\"",
    "\"return\"",
    "\"int\"",
    "\"boolean\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\".\"",
    "\";\"",
    "\",\"",
    "\"!\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"<\"",
    "\"&&\"",
    "<DIGIT>",
    "<MIN_LET>",
    "<MAI_LET>",
    "<LET>",
    "\"_\"",
    "<ID>",
    "<NUM>",
    "<REAL>",
    "<ERR>",
  };

}
