//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ericssonModel", "curiosities_fk", "category", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestMySQL.Models.category), "curiosities", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestMySQL.Models.curiosities))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ericssonModel", "collectorspoint_fk", "user", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestMySQL.Models.user), "collectorspoint", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestMySQL.Models.collectorspoint))]

// Original file name:
// Generation date: 24/3/2010 14:02:52
namespace TestMySQL.Models
{
    
    /// <summary>
    /// There are no comments for ericssonEntities in the schema.
    /// </summary>
    public partial class ericssonEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ericssonEntities object using the connection string found in the 'ericssonEntities' section of the application configuration file.
        /// </summary>
        public ericssonEntities() : 
                base("name=ericssonEntities", "ericssonEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ericssonEntities object.
        /// </summary>
        public ericssonEntities(string connectionString) : 
                base(connectionString, "ericssonEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ericssonEntities object.
        /// </summary>
        public ericssonEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ericssonEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for category in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<category> category
        {
            get
            {
                if ((this._category == null))
                {
                    this._category = base.CreateQuery<category>("[category]");
                }
                return this._category;
            }
        }
        private global::System.Data.Objects.ObjectQuery<category> _category;
        /// <summary>
        /// There are no comments for collectorspoint in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<collectorspoint> collectorspoint
        {
            get
            {
                if ((this._collectorspoint == null))
                {
                    this._collectorspoint = base.CreateQuery<collectorspoint>("[collectorspoint]");
                }
                return this._collectorspoint;
            }
        }
        private global::System.Data.Objects.ObjectQuery<collectorspoint> _collectorspoint;
        /// <summary>
        /// There are no comments for curiosities in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<curiosities> curiosities
        {
            get
            {
                if ((this._curiosities == null))
                {
                    this._curiosities = base.CreateQuery<curiosities>("[curiosities]");
                }
                return this._curiosities;
            }
        }
        private global::System.Data.Objects.ObjectQuery<curiosities> _curiosities;
        /// <summary>
        /// There are no comments for dirtypoint in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<dirtypoint> dirtypoint
        {
            get
            {
                if ((this._dirtypoint == null))
                {
                    this._dirtypoint = base.CreateQuery<dirtypoint>("[dirtypoint]");
                }
                return this._dirtypoint;
            }
        }
        private global::System.Data.Objects.ObjectQuery<dirtypoint> _dirtypoint;
        /// <summary>
        /// There are no comments for pollution in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<pollution> pollution
        {
            get
            {
                if ((this._pollution == null))
                {
                    this._pollution = base.CreateQuery<pollution>("[pollution]");
                }
                return this._pollution;
            }
        }
        private global::System.Data.Objects.ObjectQuery<pollution> _pollution;
        /// <summary>
        /// There are no comments for products in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<products> products
        {
            get
            {
                if ((this._products == null))
                {
                    this._products = base.CreateQuery<products>("[products]");
                }
                return this._products;
            }
        }
        private global::System.Data.Objects.ObjectQuery<products> _products;
        /// <summary>
        /// There are no comments for user in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<user> user
        {
            get
            {
                if ((this._user == null))
                {
                    this._user = base.CreateQuery<user>("[user]");
                }
                return this._user;
            }
        }
        private global::System.Data.Objects.ObjectQuery<user> _user;
        /// <summary>
        /// There are no comments for userdirtypoint in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<userdirtypoint> userdirtypoint
        {
            get
            {
                if ((this._userdirtypoint == null))
                {
                    this._userdirtypoint = base.CreateQuery<userdirtypoint>("[userdirtypoint]");
                }
                return this._userdirtypoint;
            }
        }
        private global::System.Data.Objects.ObjectQuery<userdirtypoint> _userdirtypoint;
        /// <summary>
        /// There are no comments for category in the schema.
        /// </summary>
        public void AddTocategory(category category)
        {
            base.AddObject("category", category);
        }
        /// <summary>
        /// There are no comments for collectorspoint in the schema.
        /// </summary>
        public void AddTocollectorspoint(collectorspoint collectorspoint)
        {
            base.AddObject("collectorspoint", collectorspoint);
        }
        /// <summary>
        /// There are no comments for curiosities in the schema.
        /// </summary>
        public void AddTocuriosities(curiosities curiosities)
        {
            base.AddObject("curiosities", curiosities);
        }
        /// <summary>
        /// There are no comments for dirtypoint in the schema.
        /// </summary>
        public void AddTodirtypoint(dirtypoint dirtypoint)
        {
            base.AddObject("dirtypoint", dirtypoint);
        }
        /// <summary>
        /// There are no comments for pollution in the schema.
        /// </summary>
        public void AddTopollution(pollution pollution)
        {
            base.AddObject("pollution", pollution);
        }
        /// <summary>
        /// There are no comments for products in the schema.
        /// </summary>
        public void AddToproducts(products products)
        {
            base.AddObject("products", products);
        }
        /// <summary>
        /// There are no comments for user in the schema.
        /// </summary>
        public void AddTouser(user user)
        {
            base.AddObject("user", user);
        }
        /// <summary>
        /// There are no comments for userdirtypoint in the schema.
        /// </summary>
        public void AddTouserdirtypoint(userdirtypoint userdirtypoint)
        {
            base.AddObject("userdirtypoint", userdirtypoint);
        }
    }
    /// <summary>
    /// There are no comments for ericssonModel.category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ericssonModel", Name="category")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class category : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new category object.
        /// </summary>
        /// <param name="description">Initial value of description.</param>
        /// <param name="id">Initial value of id.</param>
        /// <param name="type">Initial value of type.</param>
        public static category Createcategory(string description, int id, string type)
        {
            category category = new category();
            category.description = description;
            category.id = id;
            category.type = type;
            return category;
        }
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this.ReportPropertyChanging("type");
                this._type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("type");
                this.OntypeChanged();
            }
        }
        private string _type;
        partial void OntypeChanging(string value);
        partial void OntypeChanged();
        /// <summary>
        /// There are no comments for curiosities in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ericssonModel", "curiosities_fk", "curiosities")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<curiosities> curiosities
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<curiosities>("ericssonModel.curiosities_fk", "curiosities");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<curiosities>("ericssonModel.curiosities_fk", "curiosities", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ericssonModel.collectorspoint in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ericssonModel", Name="collectorspoint")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class collectorspoint : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new collectorspoint object.
        /// </summary>
        /// <param name="coordX">Initial value of coordX.</param>
        /// <param name="coordY">Initial value of coordY.</param>
        /// <param name="id">Initial value of id.</param>
        /// <param name="isValidate">Initial value of isValidate.</param>
        public static collectorspoint Createcollectorspoint(double coordX, double coordY, int id, double isValidate)
        {
            collectorspoint collectorspoint = new collectorspoint();
            collectorspoint.coordX = coordX;
            collectorspoint.coordY = coordY;
            collectorspoint.id = id;
            collectorspoint.isValidate = isValidate;
            return collectorspoint;
        }
        /// <summary>
        /// There are no comments for Property coordX in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double coordX
        {
            get
            {
                return this._coordX;
            }
            set
            {
                this.OncoordXChanging(value);
                this.ReportPropertyChanging("coordX");
                this._coordX = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coordX");
                this.OncoordXChanged();
            }
        }
        private double _coordX;
        partial void OncoordXChanging(double value);
        partial void OncoordXChanged();
        /// <summary>
        /// There are no comments for Property coordY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double coordY
        {
            get
            {
                return this._coordY;
            }
            set
            {
                this.OncoordYChanging(value);
                this.ReportPropertyChanging("coordY");
                this._coordY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coordY");
                this.OncoordYChanged();
            }
        }
        private double _coordY;
        partial void OncoordYChanging(double value);
        partial void OncoordYChanged();
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property isValidate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double isValidate
        {
            get
            {
                return this._isValidate;
            }
            set
            {
                this.OnisValidateChanging(value);
                this.ReportPropertyChanging("isValidate");
                this._isValidate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("isValidate");
                this.OnisValidateChanged();
            }
        }
        private double _isValidate;
        partial void OnisValidateChanging(double value);
        partial void OnisValidateChanged();
        /// <summary>
        /// There are no comments for user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ericssonModel", "collectorspoint_fk", "user")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public user user
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<user>("ericssonModel.collectorspoint_fk", "user").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<user>("ericssonModel.collectorspoint_fk", "user").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for user in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<user> userReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<user>("ericssonModel.collectorspoint_fk", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<user>("ericssonModel.collectorspoint_fk", "user", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ericssonModel.curiosities in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ericssonModel", Name="curiosities")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class curiosities : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new curiosities object.
        /// </summary>
        /// <param name="description">Initial value of description.</param>
        /// <param name="id">Initial value of id.</param>
        /// <param name="title">Initial value of title.</param>
        public static curiosities Createcuriosities(string description, int id, string title)
        {
            curiosities curiosities = new curiosities();
            curiosities.description = description;
            curiosities.id = id;
            curiosities.title = title;
            return curiosities;
        }
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this.OntitleChanging(value);
                this.ReportPropertyChanging("title");
                this._title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("title");
                this.OntitleChanged();
            }
        }
        private string _title;
        partial void OntitleChanging(string value);
        partial void OntitleChanged();
        /// <summary>
        /// There are no comments for category in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ericssonModel", "curiosities_fk", "category")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public category category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<category>("ericssonModel.curiosities_fk", "category").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<category>("ericssonModel.curiosities_fk", "category").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for category in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<category> categoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<category>("ericssonModel.curiosities_fk", "category");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<category>("ericssonModel.curiosities_fk", "category", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ericssonModel.dirtypoint in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ericssonModel", Name="dirtypoint")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class dirtypoint : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new dirtypoint object.
        /// </summary>
        /// <param name="coordx">Initial value of coordx.</param>
        /// <param name="coordy">Initial value of coordy.</param>
        /// <param name="id">Initial value of id.</param>
        /// <param name="pollution">Initial value of pollution.</param>
        public static dirtypoint Createdirtypoint(double coordx, double coordy, int id, int pollution)
        {
            dirtypoint dirtypoint = new dirtypoint();
            dirtypoint.coordx = coordx;
            dirtypoint.coordy = coordy;
            dirtypoint.id = id;
            dirtypoint.pollution = pollution;
            return dirtypoint;
        }
        /// <summary>
        /// There are no comments for Property coordx in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double coordx
        {
            get
            {
                return this._coordx;
            }
            set
            {
                this.OncoordxChanging(value);
                this.ReportPropertyChanging("coordx");
                this._coordx = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coordx");
                this.OncoordxChanged();
            }
        }
        private double _coordx;
        partial void OncoordxChanging(double value);
        partial void OncoordxChanged();
        /// <summary>
        /// There are no comments for Property coordy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double coordy
        {
            get
            {
                return this._coordy;
            }
            set
            {
                this.OncoordyChanging(value);
                this.ReportPropertyChanging("coordy");
                this._coordy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coordy");
                this.OncoordyChanged();
            }
        }
        private double _coordy;
        partial void OncoordyChanging(double value);
        partial void OncoordyChanged();
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property pollution in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int pollution
        {
            get
            {
                return this._pollution;
            }
            set
            {
                this.OnpollutionChanging(value);
                this.ReportPropertyChanging("pollution");
                this._pollution = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pollution");
                this.OnpollutionChanged();
            }
        }
        private int _pollution;
        partial void OnpollutionChanging(int value);
        partial void OnpollutionChanged();
    }
    /// <summary>
    /// There are no comments for ericssonModel.pollution in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ericssonModel", Name="pollution")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class pollution : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new pollution object.
        /// </summary>
        /// <param name="description">Initial value of description.</param>
        /// <param name="id">Initial value of id.</param>
        /// <param name="name">Initial value of name.</param>
        public static pollution Createpollution(string description, int id, string name)
        {
            pollution pollution = new pollution();
            pollution.description = description;
            pollution.id = id;
            pollution.name = name;
            return pollution;
        }
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
    }
    /// <summary>
    /// There are no comments for ericssonModel.products in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ericssonModel", Name="products")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class products : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new products object.
        /// </summary>
        /// <param name="degrationTime">Initial value of degrationTime.</param>
        /// <param name="id">Initial value of id.</param>
        /// <param name="name">Initial value of name.</param>
        /// <param name="photo">Initial value of photo.</param>
        public static products Createproducts(double degrationTime, int id, string name, byte[] photo)
        {
            products products = new products();
            products.degrationTime = degrationTime;
            products.id = id;
            products.name = name;
            products.photo = photo;
            return products;
        }
        /// <summary>
        /// There are no comments for Property degrationTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double degrationTime
        {
            get
            {
                return this._degrationTime;
            }
            set
            {
                this.OndegrationTimeChanging(value);
                this.ReportPropertyChanging("degrationTime");
                this._degrationTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("degrationTime");
                this.OndegrationTimeChanged();
            }
        }
        private double _degrationTime;
        partial void OndegrationTimeChanging(double value);
        partial void OndegrationTimeChanged();
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property photo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] photo
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._photo);
            }
            set
            {
                this.OnphotoChanging(value);
                this.ReportPropertyChanging("photo");
                this._photo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("photo");
                this.OnphotoChanged();
            }
        }
        private byte[] _photo;
        partial void OnphotoChanging(byte[] value);
        partial void OnphotoChanged();
    }
    /// <summary>
    /// There are no comments for ericssonModel.user in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ericssonModel", Name="user")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class user : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="login">Initial value of login.</param>
        /// <param name="name">Initial value of name.</param>
        /// <param name="password">Initial value of password.</param>
        /// <param name="points">Initial value of points.</param>
        /// <param name="reputation">Initial value of reputation.</param>
        public static user Createuser(int id, string login, string name, string password, double points, double reputation)
        {
            user user = new user();
            user.id = id;
            user.login = login;
            user.name = name;
            user.password = password;
            user.points = points;
            user.reputation = reputation;
            return user;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property login in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string login
        {
            get
            {
                return this._login;
            }
            set
            {
                this.OnloginChanging(value);
                this.ReportPropertyChanging("login");
                this._login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("login");
                this.OnloginChanged();
            }
        }
        private string _login;
        partial void OnloginChanging(string value);
        partial void OnloginChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                this.OnpasswordChanging(value);
                this.ReportPropertyChanging("password");
                this._password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("password");
                this.OnpasswordChanged();
            }
        }
        private string _password;
        partial void OnpasswordChanging(string value);
        partial void OnpasswordChanged();
        /// <summary>
        /// There are no comments for Property photo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] photo
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._photo);
            }
            set
            {
                this.OnphotoChanging(value);
                this.ReportPropertyChanging("photo");
                this._photo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("photo");
                this.OnphotoChanged();
            }
        }
        private byte[] _photo;
        partial void OnphotoChanging(byte[] value);
        partial void OnphotoChanged();
        /// <summary>
        /// There are no comments for Property points in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double points
        {
            get
            {
                return this._points;
            }
            set
            {
                this.OnpointsChanging(value);
                this.ReportPropertyChanging("points");
                this._points = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("points");
                this.OnpointsChanged();
            }
        }
        private double _points;
        partial void OnpointsChanging(double value);
        partial void OnpointsChanged();
        /// <summary>
        /// There are no comments for Property reputation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double reputation
        {
            get
            {
                return this._reputation;
            }
            set
            {
                this.OnreputationChanging(value);
                this.ReportPropertyChanging("reputation");
                this._reputation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("reputation");
                this.OnreputationChanged();
            }
        }
        private double _reputation;
        partial void OnreputationChanging(double value);
        partial void OnreputationChanged();
        /// <summary>
        /// There are no comments for Property whoami in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string whoami
        {
            get
            {
                return this._whoami;
            }
            set
            {
                this.OnwhoamiChanging(value);
                this.ReportPropertyChanging("whoami");
                this._whoami = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("whoami");
                this.OnwhoamiChanged();
            }
        }
        private string _whoami;
        partial void OnwhoamiChanging(string value);
        partial void OnwhoamiChanged();
        /// <summary>
        /// There are no comments for collectorspoint in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ericssonModel", "collectorspoint_fk", "collectorspoint")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<collectorspoint> collectorspoint
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<collectorspoint>("ericssonModel.collectorspoint_fk", "collectorspoint");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<collectorspoint>("ericssonModel.collectorspoint_fk", "collectorspoint", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ericssonModel.userdirtypoint in the schema.
    /// </summary>
    /// <KeyProperties>
    /// dirtypoint
    /// pointstoreceive
    /// user
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ericssonModel", Name="userdirtypoint")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class userdirtypoint : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new userdirtypoint object.
        /// </summary>
        /// <param name="dirtypoint">Initial value of dirtypoint.</param>
        /// <param name="pointstoreceive">Initial value of pointstoreceive.</param>
        /// <param name="user">Initial value of user.</param>
        public static userdirtypoint Createuserdirtypoint(int dirtypoint, double pointstoreceive, int user)
        {
            userdirtypoint userdirtypoint = new userdirtypoint();
            userdirtypoint.dirtypoint = dirtypoint;
            userdirtypoint.pointstoreceive = pointstoreceive;
            userdirtypoint.user = user;
            return userdirtypoint;
        }
        /// <summary>
        /// There are no comments for Property dirtypoint in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int dirtypoint
        {
            get
            {
                return this._dirtypoint;
            }
            set
            {
                this.OndirtypointChanging(value);
                this.ReportPropertyChanging("dirtypoint");
                this._dirtypoint = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dirtypoint");
                this.OndirtypointChanged();
            }
        }
        private int _dirtypoint;
        partial void OndirtypointChanging(int value);
        partial void OndirtypointChanged();
        /// <summary>
        /// There are no comments for Property pointstoreceive in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double pointstoreceive
        {
            get
            {
                return this._pointstoreceive;
            }
            set
            {
                this.OnpointstoreceiveChanging(value);
                this.ReportPropertyChanging("pointstoreceive");
                this._pointstoreceive = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pointstoreceive");
                this.OnpointstoreceiveChanged();
            }
        }
        private double _pointstoreceive;
        partial void OnpointstoreceiveChanging(double value);
        partial void OnpointstoreceiveChanged();
        /// <summary>
        /// There are no comments for Property user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int user
        {
            get
            {
                return this._user;
            }
            set
            {
                this.OnuserChanging(value);
                this.ReportPropertyChanging("user");
                this._user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user");
                this.OnuserChanged();
            }
        }
        private int _user;
        partial void OnuserChanging(int value);
        partial void OnuserChanged();
    }
}
