//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("hotelModel", "ClientCheck", "Client", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hotel.Models.Client), "Check", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hotel.Models.Check))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("hotelModel", "ApartmentCheck", "Apartment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hotel.Models.Apartment), "Check", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hotel.Models.Check))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("hotelModel", "ApartmentApartmentType", "Apartment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hotel.Models.Apartment), "ApartmentType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hotel.Models.ApartmentType))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("hotelModel", "ExpenseCheck", "Expense", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hotel.Models.Expense), "Check", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hotel.Models.Check))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("hotelModel", "ExpenseService", "Expense", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Hotel.Models.Expense), "Service", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Hotel.Models.Service))]

// Original file name:
// Generation date: 27/5/2010 02:13:57
namespace Hotel.Models
{
    
    /// <summary>
    /// There are no comments for hotelEntities in the schema.
    /// </summary>
    public partial class hotelEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new hotelEntities object using the connection string found in the 'hotelEntities' section of the application configuration file.
        /// </summary>
        public hotelEntities() : 
                base("name=hotelEntities", "hotelEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new hotelEntities object.
        /// </summary>
        public hotelEntities(string connectionString) : 
                base(connectionString, "hotelEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new hotelEntities object.
        /// </summary>
        public hotelEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "hotelEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for InnSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Inn> InnSet
        {
            get
            {
                if ((this._InnSet == null))
                {
                    this._InnSet = base.CreateQuery<Inn>("[InnSet]");
                }
                return this._InnSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Inn> _InnSet;
        /// <summary>
        /// There are no comments for PersonSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Person> PersonSet
        {
            get
            {
                if ((this._PersonSet == null))
                {
                    this._PersonSet = base.CreateQuery<Person>("[PersonSet]");
                }
                return this._PersonSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Person> _PersonSet;
        /// <summary>
        /// There are no comments for ServiceSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Service> ServiceSet
        {
            get
            {
                if ((this._ServiceSet == null))
                {
                    this._ServiceSet = base.CreateQuery<Service>("[ServiceSet]");
                }
                return this._ServiceSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Service> _ServiceSet;
        /// <summary>
        /// There are no comments for ApartmentSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Apartment> ApartmentSet
        {
            get
            {
                if ((this._ApartmentSet == null))
                {
                    this._ApartmentSet = base.CreateQuery<Apartment>("[ApartmentSet]");
                }
                return this._ApartmentSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Apartment> _ApartmentSet;
        /// <summary>
        /// There are no comments for ApartmentTypeSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ApartmentType> ApartmentTypeSet
        {
            get
            {
                if ((this._ApartmentTypeSet == null))
                {
                    this._ApartmentTypeSet = base.CreateQuery<ApartmentType>("[ApartmentTypeSet]");
                }
                return this._ApartmentTypeSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ApartmentType> _ApartmentTypeSet;
        /// <summary>
        /// There are no comments for CheckSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Check> CheckSet
        {
            get
            {
                if ((this._CheckSet == null))
                {
                    this._CheckSet = base.CreateQuery<Check>("[CheckSet]");
                }
                return this._CheckSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Check> _CheckSet;
        /// <summary>
        /// There are no comments for ExpenseSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Expense> ExpenseSet
        {
            get
            {
                if ((this._ExpenseSet == null))
                {
                    this._ExpenseSet = base.CreateQuery<Expense>("[ExpenseSet]");
                }
                return this._ExpenseSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Expense> _ExpenseSet;
        /// <summary>
        /// There are no comments for InnSet in the schema.
        /// </summary>
        public void AddToInnSet(Inn inn)
        {
            base.AddObject("InnSet", inn);
        }
        /// <summary>
        /// There are no comments for PersonSet in the schema.
        /// </summary>
        public void AddToPersonSet(Person person)
        {
            base.AddObject("PersonSet", person);
        }
        /// <summary>
        /// There are no comments for ServiceSet in the schema.
        /// </summary>
        public void AddToServiceSet(Service service)
        {
            base.AddObject("ServiceSet", service);
        }
        /// <summary>
        /// There are no comments for ApartmentSet in the schema.
        /// </summary>
        public void AddToApartmentSet(Apartment apartment)
        {
            base.AddObject("ApartmentSet", apartment);
        }
        /// <summary>
        /// There are no comments for ApartmentTypeSet in the schema.
        /// </summary>
        public void AddToApartmentTypeSet(ApartmentType apartmentType)
        {
            base.AddObject("ApartmentTypeSet", apartmentType);
        }
        /// <summary>
        /// There are no comments for CheckSet in the schema.
        /// </summary>
        public void AddToCheckSet(Check check)
        {
            base.AddObject("CheckSet", check);
        }
        /// <summary>
        /// There are no comments for ExpenseSet in the schema.
        /// </summary>
        public void AddToExpenseSet(Expense expense)
        {
            base.AddObject("ExpenseSet", expense);
        }
    }
    /// <summary>
    /// There are no comments for hotelModel.Client in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Client")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Client : Person
    {
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Client CreateClient(int id)
        {
            Client client = new Client();
            client.ID = id;
            return client;
        }
        /// <summary>
        /// There are no comments for Property Login in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this._Login;
            }
            set
            {
                this.OnLoginChanging(value);
                this.ReportPropertyChanging("Login");
                this._Login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Login");
                this.OnLoginChanged();
            }
        }
        private string _Login;
        partial void OnLoginChanging(string value);
        partial void OnLoginChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Check in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ClientCheck", "Check")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Check> Check
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Check>("hotelModel.ClientCheck", "Check");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Check>("hotelModel.ClientCheck", "Check", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for hotelModel.Inn in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Inn")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Inn : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Inn object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        public static Inn CreateInn(string name)
        {
            Inn inn = new Inn();
            inn.Name = name;
            return inn;
        }
        /// <summary>
        /// There are no comments for Property Logo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo
        {
            get
            {
                return this._Logo;
            }
            set
            {
                this.OnLogoChanging(value);
                this.ReportPropertyChanging("Logo");
                this._Logo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Logo");
                this.OnLogoChanged();
            }
        }
        private string _Logo;
        partial void OnLogoChanging(string value);
        partial void OnLogoChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for hotelModel.Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Person")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::Hotel.Models.Client))]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::Hotel.Models.Employee))]
    public partial class Person : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Person CreatePerson(int id)
        {
            Person person = new Person();
            person.ID = id;
            return person;
        }
        /// <summary>
        /// There are no comments for Property DateOfBirth in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this.OnDateOfBirthChanging(value);
                this.ReportPropertyChanging("DateOfBirth");
                this._DateOfBirth = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateOfBirth");
                this.OnDateOfBirthChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CPF in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF
        {
            get
            {
                return this._CPF;
            }
            set
            {
                this.OnCPFChanging(value);
                this.ReportPropertyChanging("CPF");
                this._CPF = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CPF");
                this.OnCPFChanged();
            }
        }
        private string _CPF;
        partial void OnCPFChanging(string value);
        partial void OnCPFChanged();
    }
    /// <summary>
    /// There are no comments for hotelModel.Service in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Service")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Service : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Service object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="price">Initial value of Price.</param>
        public static Service CreateService(int id, string name, double price)
        {
            Service service = new Service();
            service.ID = id;
            service.Name = name;
            service.Price = price;
            return service;
        }
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this.ReportPropertyChanging("Price");
                this._Price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Price");
                this.OnPriceChanged();
            }
        }
        private double _Price;
        partial void OnPriceChanging(double value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Expense in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ExpenseService", "Expense")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Expense> Expense
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Expense>("hotelModel.ExpenseService", "Expense");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Expense>("hotelModel.ExpenseService", "Expense", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for hotelModel.Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Employee")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Employee : Person
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="login">Initial value of Login.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="type">Initial value of Type.</param>
        public static Employee CreateEmployee(int id, string login, string password, int type)
        {
            Employee employee = new Employee();
            employee.ID = id;
            employee.Login = login;
            employee.Password = password;
            employee.Type = type;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property Login in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this._Login;
            }
            set
            {
                this.OnLoginChanging(value);
                this.ReportPropertyChanging("Login");
                this._Login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Login");
                this.OnLoginChanged();
            }
        }
        private string _Login;
        partial void OnLoginChanging(string value);
        partial void OnLoginChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this.ReportPropertyChanging("Type");
                this._Type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Type");
                this.OnTypeChanged();
            }
        }
        private int _Type;
        partial void OnTypeChanging(int value);
        partial void OnTypeChanged();
    }
    /// <summary>
    /// There are no comments for hotelModel.Apartment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Apartment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Apartment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Apartment object.
        /// </summary>
        /// <param name="floor">Initial value of Floor.</param>
        /// <param name="number">Initial value of Number.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="id">Initial value of ID.</param>
        public static Apartment CreateApartment(int floor, int number, int status, int id)
        {
            Apartment apartment = new Apartment();
            apartment.Floor = floor;
            apartment.Number = number;
            apartment.Status = status;
            apartment.ID = id;
            return apartment;
        }
        /// <summary>
        /// There are no comments for Property Floor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Floor
        {
            get
            {
                return this._Floor;
            }
            set
            {
                this.OnFloorChanging(value);
                this.ReportPropertyChanging("Floor");
                this._Floor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Floor");
                this.OnFloorChanged();
            }
        }
        private int _Floor;
        partial void OnFloorChanging(int value);
        partial void OnFloorChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this.ReportPropertyChanging("Number");
                this._Number = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Number");
                this.OnNumberChanged();
            }
        }
        private int _Number;
        partial void OnNumberChanging(int value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Check in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ApartmentCheck", "Check")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Check> Check
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Check>("hotelModel.ApartmentCheck", "Check");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Check>("hotelModel.ApartmentCheck", "Check", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ApartmentType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ApartmentApartmentType", "ApartmentType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ApartmentType ApartmentType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ApartmentType>("hotelModel.ApartmentApartmentType", "ApartmentType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ApartmentType>("hotelModel.ApartmentApartmentType", "ApartmentType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ApartmentType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ApartmentType> ApartmentTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ApartmentType>("hotelModel.ApartmentApartmentType", "ApartmentType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ApartmentType>("hotelModel.ApartmentApartmentType", "ApartmentType", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for hotelModel.ApartmentType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="ApartmentType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ApartmentType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ApartmentType object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static ApartmentType CreateApartmentType(int id, string name)
        {
            ApartmentType apartmentType = new ApartmentType();
            apartmentType.ID = id;
            apartmentType.Name = name;
            return apartmentType;
        }
        /// <summary>
        /// There are no comments for Property Bed in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Bed
        {
            get
            {
                return this._Bed;
            }
            set
            {
                this.OnBedChanging(value);
                this.ReportPropertyChanging("Bed");
                this._Bed = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Bed");
                this.OnBedChanged();
            }
        }
        private global::System.Nullable<int> _Bed;
        partial void OnBedChanging(global::System.Nullable<int> value);
        partial void OnBedChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this.ReportPropertyChanging("Price");
                this._Price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Price");
                this.OnPriceChanged();
            }
        }
        private global::System.Nullable<double> _Price;
        partial void OnPriceChanging(global::System.Nullable<double> value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Apartment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ApartmentApartmentType", "Apartment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Apartment> Apartment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Apartment>("hotelModel.ApartmentApartmentType", "Apartment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Apartment>("hotelModel.ApartmentApartmentType", "Apartment", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for hotelModel.Check in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Check")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Check : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Check object.
        /// </summary>
        /// <param name="dateBegin">Initial value of DateBegin.</param>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="value">Initial value of Value.</param>
        public static Check CreateCheck(global::System.DateTime dateBegin, int id, int status, double value)
        {
            Check check = new Check();
            check.DateBegin = dateBegin;
            check.ID = id;
            check.Status = status;
            check.Value = value;
            return check;
        }
        /// <summary>
        /// There are no comments for Property DateBegin in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime DateBegin
        {
            get
            {
                return this._DateBegin;
            }
            set
            {
                this.OnDateBeginChanging(value);
                this.ReportPropertyChanging("DateBegin");
                this._DateBegin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateBegin");
                this.OnDateBeginChanged();
            }
        }
        private global::System.DateTime _DateBegin;
        partial void OnDateBeginChanging(global::System.DateTime value);
        partial void OnDateBeginChanged();
        /// <summary>
        /// There are no comments for Property DateEnd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateEnd
        {
            get
            {
                return this._DateEnd;
            }
            set
            {
                this.OnDateEndChanging(value);
                this.ReportPropertyChanging("DateEnd");
                this._DateEnd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateEnd");
                this.OnDateEndChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateEnd;
        partial void OnDateEndChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateEndChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private double _Value;
        partial void OnValueChanging(double value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Client in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ClientCheck", "Client")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Client Client
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Client>("hotelModel.ClientCheck", "Client").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Client>("hotelModel.ClientCheck", "Client").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Client in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Client> ClientReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Client>("hotelModel.ClientCheck", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Client>("hotelModel.ClientCheck", "Client", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Apartment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ApartmentCheck", "Apartment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Apartment Apartment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Apartment>("hotelModel.ApartmentCheck", "Apartment").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Apartment>("hotelModel.ApartmentCheck", "Apartment").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Apartment in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Apartment> ApartmentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Apartment>("hotelModel.ApartmentCheck", "Apartment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Apartment>("hotelModel.ApartmentCheck", "Apartment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Expense in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ExpenseCheck", "Expense")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Expense> Expense
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Expense>("hotelModel.ExpenseCheck", "Expense");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Expense>("hotelModel.ExpenseCheck", "Expense", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for hotelModel.Expense in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="hotelModel", Name="Expense")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Expense : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Expense object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="amount">Initial value of Amount.</param>
        public static Expense CreateExpense(int id, double value, int amount)
        {
            Expense expense = new Expense();
            expense.ID = id;
            expense.Value = value;
            expense.Amount = amount;
            return expense;
        }
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private double _Value;
        partial void OnValueChanging(double value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this.ReportPropertyChanging("Amount");
                this._Amount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Amount");
                this.OnAmountChanged();
            }
        }
        private int _Amount;
        partial void OnAmountChanging(int value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for Check in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ExpenseCheck", "Check")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Check Check
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Check>("hotelModel.ExpenseCheck", "Check").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Check>("hotelModel.ExpenseCheck", "Check").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Check in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Check> CheckReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Check>("hotelModel.ExpenseCheck", "Check");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Check>("hotelModel.ExpenseCheck", "Check", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Service in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("hotelModel", "ExpenseService", "Service")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Service Service
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Service>("hotelModel.ExpenseService", "Service").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Service>("hotelModel.ExpenseService", "Service").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Service in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Service> ServiceReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Service>("hotelModel.ExpenseService", "Service");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Service>("hotelModel.ExpenseService", "Service", value);
                }
            }
        }
    }
}
